### ISSUE TITLE
some warning

### ISSUE THREAD

**Issue by Hunlongyu** [rmisev/url_whatwg#45]
Download the latest url.h and url.cpp files from the release, and when introduced for use on Windows 11 with Visual Studio 2022, an error message is displayed:
"Cannot find directory 'unicode' in search paths:"

**Comment by Hunlongyu** [comment]
![image](https://github.com/rmisev/url_whatwg/assets/15273630/61c27010-7c33-414b-a3ba-af132548e39e)

**Comment by rmisev** [comment]
To use this library, you must have the ICU library installed. I think the easiest way is to install it with the **vcpkg** package manager: https://vcpkg.io/en/. It integrates well with Visual Studio.

Alternatively, you can download the ICU library from the releases page: https://github.com/unicode-org/icu/releases
(download `icu4c-75_1-Win64-MSVC2022.zip` or `icu4c-75_1-Win32-MSVC2022.zip` for the latest version).
Extract the downloaded file to your preferred directory, and then specify the ICU include directory and library files (`icuuc.lib` and `icuin.lib`) in your project settings. Add the ICU `bin64` (or `bin`) directory to the `PATH`, or copy the `icudt75.dll`, `icuin75.dll` and `icuuc75.dll` files to the directory added to the `PATH`.

Notes:
1. ICU 75.1 requires C++17 or later. Earlier versions of ICU require C++11 or later.
2. [The ICU library bundled with Windows 10 or 11](https://learn.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-) is not currently supported.

**Comment by Hunlongyu** [comment]
😘 3q
